@startuml

class Lampe{
    -nom : String
    -allume : boolean
    +Lampe(nom : String) : Lampe
    +allumer() : void
    +eteindre() : void
    +toString() : String
}

class Telecommande{

    +Telecommande(lampe : Lampe) : Telecommande
    +ajouterLampe(Lampe lampe) : void
    +ajouterHifi(Hifi hifi) : void
    +activerLampe(int indiceLampe) : void
    +activerHifi(int indicehifi) : void
    +desactiverLampe(int indiceLampe) : void
    +desactiverHifi(int indicehifi) : void
    +activerTout() : void
    +desactiverTout() : void
    +toString() : String
}

class Hifi{
    -son : int
    +allumer() : void
    +eteindre() : void
    +toString() : String
}


Lampe "*" <-- "*" Telecommande : - lampes
Hifi "*" <-- "*" Telecommande : - hifis

@enduml